#!/usr/bin/env pwsh
# GENESIS PRIME - Deterministic One-Command Build & Start
# Intelligent automated workflow with memory-mode fallback and full MCP integration

param(
    [switch]$SkipBuild,
    [switch]$SkipVerify,
    [switch]$DockerMode,
    [switch]$Verbose,
    [switch]$GenerateEvidence
)

$ErrorActionPreference = "Stop"
$StartTime = Get-Date
$RunId = "genesis-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
$EvidenceDir = "evidence/$RunId"

# Colors for output
function Write-Phase { param($msg) Write-Host "`n✨ $msg" -ForegroundColor Cyan }
function Write-Success { param($msg) Write-Host "✅ $msg" -ForegroundColor Green }
function Write-Warning { param($msg) Write-Host "⚠️  $msg" -ForegroundColor Yellow }
function Write-Error { param($msg) Write-Host "❌ $msg" -ForegroundColor Red }
function Write-Info { param($msg) Write-Host "ℹ️  $msg" -ForegroundColor Gray }

# Evidence collection
$Evidence = @{
    RunId = $RunId
    StartTime = $StartTime
    Environment = @{}
    BuildResults = @{}
    HealthChecks = @{}
    Errors = @()
}

# Capture system state
function Capture-SystemState {
    $Evidence.Environment = @{
        NodeVersion = node --version 2>$null
        PnpmVersion = pnpm --version 2>$null
        GitCommit = git rev-parse HEAD 2>$null
        GitBranch = git branch --show-current 2>$null
        Platform = $PSVersionTable.Platform
        WorkingDirectory = $PWD.Path
    }
}

# Check prerequisites
function Test-Prerequisites {
    Write-Phase "PHASE 0: Prerequisites Check"
    
    $missing = @()
    
    # Node.js
    if (!(Get-Command node -ErrorAction SilentlyContinue)) {
        $missing += "Node.js"
    } else {
        Write-Success "Node.js: $(node --version)"
    }
    
    # pnpm
    if (!(Get-Command pnpm -ErrorAction SilentlyContinue)) {
        $missing += "pnpm"
    } else {
        Write-Success "pnpm: $(pnpm --version)"
    }
    
    # Git
    if (!(Get-Command git -ErrorAction SilentlyContinue)) {
        $missing += "Git"
    } else {
        Write-Success "Git: $(git --version)"
    }
    
    if ($DockerMode) {
        if (!(Get-Command docker -ErrorAction SilentlyContinue)) {
            $missing += "Docker"
        } else {
            $dockerRunning = docker info 2>$null
            if (!$dockerRunning) {
                Write-Warning "Docker is installed but not running"
                $missing += "Docker (not running)"
            } else {
                Write-Success "Docker: Running"
            }
        }
    }
    
    if ($missing.Count -gt 0) {
        Write-Error "Missing prerequisites: $($missing -join ', ')"
        exit 1
    }
    
    $Evidence.HealthChecks.Prerequisites = "Passed"
}

# Setup environment
function Setup-Environment {
    Write-Phase "PHASE 1: Environment Setup"
    
    # Check for .env.local
    if (Test-Path ".env.local") {
        Write-Success "Found .env.local"
        Get-Content ".env.local" | ForEach-Object {
            if ($_ -match '^([^=]+)=(.*)$') {
                $key = $matches[1]
                $value = $matches[2]
                [Environment]::SetEnvironmentVariable($key, $value)
                if ($key -notlike "*KEY*" -and $key -notlike "*TOKEN*") {
                    Write-Info "Set: $key"
                } else {
                    Write-Info "Set: $key=***"
                }
            }
        }
    } else {
        Write-Warning "No .env.local found - creating minimal config"
        @"
# Heady Systems Environment Configuration
# Generated by genesis-prime.ps1

# Core API Key (required for protected routes)
HC_AUTOMATION_API_KEY=genesis-local-$(Get-Random -Maximum 999999)

# MCP Services (optional - add your keys here)
# ANTHROPIC_API_KEY=sk-ant-...
# GITHUB_TOKEN=ghp_...
# HUGGINGFACE_TOKEN=hf_...

# Infrastructure Mode
INFRASTRUCTURE_MODE=memory
"@ | Out-File -FilePath ".env.local" -Encoding utf8
        Write-Success "Created .env.local with default values"
    }
    
    # Set default port based on mode
    if ($DockerMode) {
        [Environment]::SetEnvironmentVariable("PORT", "3000")
        [Environment]::SetEnvironmentVariable("API_PORT", "3000")
        Write-Info "Docker mode: API port 3000"
    } else {
        [Environment]::SetEnvironmentVariable("PORT", "4100")
        [Environment]::SetEnvironmentVariable("API_PORT", "4100")
        Write-Info "Native mode: API port 4100"
    }
    
    $Evidence.Environment.Mode = if ($DockerMode) { "Docker" } else { "Native" }
}

# Install dependencies
function Install-Dependencies {
    Write-Phase "PHASE 2: Dependencies Installation"
    
    try {
        Write-Info "Installing dependencies with pnpm..."
        $output = pnpm install --frozen-lockfile 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Success "Dependencies installed successfully"
        } else {
            Write-Warning "Frozen lockfile failed, trying regular install..."
            pnpm install
            Write-Success "Dependencies installed (lockfile updated)"
        }
        $Evidence.BuildResults.Dependencies = "Installed"
    } catch {
        Write-Error "Failed to install dependencies: $_"
        $Evidence.Errors += "Dependencies: $_"
        exit 1
    }
}

# Build project
function Build-Project {
    if ($SkipBuild) {
        Write-Warning "Skipping build phase"
        return
    }
    
    Write-Phase "PHASE 3: Building Project"
    
    try {
        Write-Info "Building all packages and apps..."
        $buildStart = Get-Date
        pnpm build
        $buildDuration = (Get-Date) - $buildStart
        
        Write-Success "Build completed in $($buildDuration.TotalSeconds) seconds"
        $Evidence.BuildResults.Duration = $buildDuration.TotalSeconds
        $Evidence.BuildResults.Status = "Success"
        
        # Verify build outputs
        $criticalOutputs = @(
            "packages/core-domain/dist/mcp-server.js",
            "packages/task-manager/dist/index.js",
            "packages/ui/dist/index.js",
            "apps/heady-automation-ide/dist/server/index.js"
        )
        
        $missingOutputs = @()
        foreach ($output in $criticalOutputs) {
            if (!(Test-Path $output)) {
                $missingOutputs += $output
            }
        }
        
        if ($missingOutputs.Count -gt 0) {
            Write-Warning "Some build outputs are missing:"
            $missingOutputs | ForEach-Object { Write-Warning "  - $_" }
        } else {
            Write-Success "All critical build outputs verified"
        }
        
    } catch {
        Write-Error "Build failed: $_"
        $Evidence.Errors += "Build: $_"
        exit 1
    }
}

# Verify MCP functionality
function Test-MCP {
    if ($SkipVerify) {
        Write-Warning "Skipping MCP verification"
        return
    }
    
    Write-Phase "PHASE 4: MCP Verification"
    
    # First build core-domain if needed
    if (!(Test-Path "packages/core-domain/dist/mcp-server.js")) {
        Write-Info "Building core-domain for MCP server..."
        Push-Location packages/core-domain
        pnpm build
        Pop-Location
    }
    
    try {
        Write-Info "Testing Heady MCP server..."
        $mcpTest = node scripts/verify-mcp-new.js 2>&1
        
        if ($LASTEXITCODE -eq 0) {
            Write-Success "MCP server verification passed"
            $Evidence.HealthChecks.MCP = "Verified"
        } else {
            Write-Warning "MCP verification had issues but continuing..."
            $Evidence.HealthChecks.MCP = "Partial"
        }
        
        if ($Verbose) {
            Write-Info "MCP Test Output:"
            $mcpTest | ForEach-Object { Write-Host "  $_" -ForegroundColor Gray }
        }
    } catch {
        Write-Warning "MCP verification failed (non-critical): $_"
        $Evidence.HealthChecks.MCP = "Failed"
    }
}

# Start services
function Start-Services {
    Write-Phase "PHASE 5: Starting Services"
    
    if ($DockerMode) {
        Write-Info "Starting Docker infrastructure..."
        docker-compose up -d db redis otel-collector
        Start-Sleep -Seconds 5
        Write-Success "Docker services started"
    }
    
    # Start in background
    Write-Info "Starting Heady Systems (this will run in foreground)..."
    Write-Success "All services starting..."
    Write-Host ""
    Write-Host "🚀 GENESIS PRIME INITIALIZATION COMPLETE" -ForegroundColor Green
    Write-Host ""
    Write-Host "Services starting on:" -ForegroundColor Cyan
    if ($DockerMode) {
        Write-Host "  • API:        http://localhost:3000/api/health" -ForegroundColor White
        Write-Host "  • IDE:        http://localhost:5173" -ForegroundColor White
        Write-Host "  • Connection: http://localhost:3002" -ForegroundColor White
        Write-Host "  • Systems:    http://localhost:3003" -ForegroundColor White
    } else {
        Write-Host "  • API:        http://localhost:4100/api/health" -ForegroundColor White
        Write-Host "  • IDE:        http://localhost:5173" -ForegroundColor White
        Write-Host "  • Connection: http://localhost:3002" -ForegroundColor White
        Write-Host "  • Systems:    http://localhost:3003" -ForegroundColor White
    }
    Write-Host ""
    Write-Host "Press Ctrl+C to stop all services" -ForegroundColor Yellow
    Write-Host ""
    
    # Generate evidence if requested
    if ($GenerateEvidence) {
        Save-Evidence
    }
    
    # Start the dev server
    pnpm dev
}

# Save evidence pack
function Save-Evidence {
    if (!(Test-Path "evidence")) {
        New-Item -ItemType Directory -Path "evidence" | Out-Null
    }
    
    New-Item -ItemType Directory -Path $EvidenceDir | Out-Null
    
    $Evidence.EndTime = Get-Date
    $Evidence.Duration = ($Evidence.EndTime - $Evidence.StartTime).TotalSeconds
    
    # Save as JSON
    $Evidence | ConvertTo-Json -Depth 10 | Out-File "$EvidenceDir/evidence.json"
    
    # Save build log
    if (Test-Path "pnpm-debug.log") {
        Copy-Item "pnpm-debug.log" "$EvidenceDir/"
    }
    
    # Hash important files
    $hashes = @{}
    @("pnpm-lock.yaml", "package.json", ".env.local") | ForEach-Object {
        if (Test-Path $_) {
            $hash = (Get-FileHash $_ -Algorithm SHA256).Hash
            $hashes[$_] = $hash
        }
    }
    $hashes | ConvertTo-Json | Out-File "$EvidenceDir/hashes.json"
    
    Write-Success "Evidence pack saved to $EvidenceDir"
}

# Main execution flow
function Main {
    Write-Host ""
    Write-Host "🌟 GENESIS PRIME - Heady Systems Automated Build & Start" -ForegroundColor Magenta
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Magenta
    Write-Host "Run ID: $RunId" -ForegroundColor Gray
    Write-Host ""
    
    Capture-SystemState
    Test-Prerequisites
    Setup-Environment
    Install-Dependencies
    Build-Project
    Test-MCP
    Start-Services
}

# Error handler
trap {
    Write-Error "Fatal error: $_"
    $Evidence.Errors += "Fatal: $_"
    if ($GenerateEvidence) {
        Save-Evidence
    }
    exit 1
}

# Run
Main
